### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by guillenotfound** [Rawi01/cordova-plugin-googlemaps-cluster#1]
Hey!

First of all thank you for this implementation.

I've been trying this for a while and I'm unable to get this working, can you provide an example repository with basic functionality?

Thanks :)

**Comment by Rawi01** [comment]
Sure, just created a quick and dirty demo app: https://github.com/Rawi01/cluster-example

**Comment by guillenotfound** [comment]
It works! We have +600 markers and this almost fixes our performance issues :)

Thank you very much!!!
